[2022-10-17 10:26:44,909] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.process_user manual__2022-10-17T10:26:39.021374+00:00 [queued]>
[2022-10-17 10:26:44,915] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.process_user manual__2022-10-17T10:26:39.021374+00:00 [queued]>
[2022-10-17 10:26:44,915] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:26:44,916] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:26:44,916] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:26:44,924] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_user> on 2022-10-17 10:26:39.021374+00:00
[2022-10-17 10:26:44,929] {standard_task_runner.py:52} INFO - Started process 3650 to run task
[2022-10-17 10:26:44,932] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'process_user', 'manual__2022-10-17T10:26:39.021374+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpn8v3_pxu', '--error-file', '/tmp/tmpb6t_tmo2']
[2022-10-17 10:26:44,933] {standard_task_runner.py:80} INFO - Job 84: Subtask process_user
[2022-10-17 10:26:44,967] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.process_user manual__2022-10-17T10:26:39.021374+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:26:45,010] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T10:26:39.021374+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-17T10:26:39.021374+00:00
[2022-10-17 10:26:45,030] {python.py:173} INFO - Done. Returned value was: None
[2022-10-17 10:26:45,038] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=process_user, execution_date=20221017T102639, start_date=20221017T102644, end_date=20221017T102645
[2022-10-17 10:26:45,065] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:26:45,088] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
