[2022-10-17 10:48:45,714] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.store_user backfill__2022-01-12T00:00:00+00:00 [queued]>
[2022-10-17 10:48:45,745] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.store_user backfill__2022-01-12T00:00:00+00:00 [queued]>
[2022-10-17 10:48:45,749] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:48:45,750] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:48:45,750] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:48:45,787] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-01-12 00:00:00+00:00
[2022-10-17 10:48:45,793] {standard_task_runner.py:52} INFO - Started process 4919 to run task
[2022-10-17 10:48:45,814] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'store_user', 'backfill__2022-01-12T00:00:00+00:00', '--job-id', '178', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmptc289kkn', '--error-file', '/tmp/tmpvz3rt41f']
[2022-10-17 10:48:45,826] {standard_task_runner.py:80} INFO - Job 178: Subtask store_user
[2022-10-17 10:48:46,046] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.store_user backfill__2022-01-12T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:48:46,263] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-01-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-01-12T00:00:00+00:00
[2022-10-17 10:48:46,268] {postgres.py:127} INFO - Running copy expert: COPY users2 FROM stdin WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2022-10-17 10:48:46,298] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-17 10:48:46,331] {python.py:173} INFO - Done. Returned value was: None
[2022-10-17 10:48:46,371] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=store_user, execution_date=20220112T000000, start_date=20221017T104845, end_date=20221017T104846
[2022-10-17 10:48:46,517] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:48:46,615] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
