[2022-10-17 10:33:00,668] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.process_user manual__2022-10-17T10:32:54.309653+00:00 [queued]>
[2022-10-17 10:33:00,675] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.process_user manual__2022-10-17T10:32:54.309653+00:00 [queued]>
[2022-10-17 10:33:00,676] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:33:00,676] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 10:33:00,676] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 10:33:00,688] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_user> on 2022-10-17 10:32:54.309653+00:00
[2022-10-17 10:33:00,693] {standard_task_runner.py:52} INFO - Started process 3972 to run task
[2022-10-17 10:33:00,696] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'process_user', 'manual__2022-10-17T10:32:54.309653+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppvtxql2a', '--error-file', '/tmp/tmpj2ecbzzp']
[2022-10-17 10:33:00,697] {standard_task_runner.py:80} INFO - Job 103: Subtask process_user
[2022-10-17 10:33:00,739] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.process_user manual__2022-10-17T10:32:54.309653+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 10:33:00,794] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T10:32:54.309653+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-17T10:32:54.309653+00:00
[2022-10-17 10:33:00,816] {python.py:173} INFO - Done. Returned value was: None
[2022-10-17 10:33:00,830] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=process_user, execution_date=20221017T103254, start_date=20221017T103300, end_date=20221017T103300
[2022-10-17 10:33:00,869] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 10:33:00,924] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
