[2022-10-17 09:34:02,808] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-09-17T00:00:00+00:00 [queued]>
[2022-10-17 09:34:02,836] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_table backfill__2022-09-17T00:00:00+00:00 [queued]>
[2022-10-17 09:34:02,838] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 09:34:02,839] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-17 09:34:02,839] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 09:34:02,939] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-17 00:00:00+00:00
[2022-10-17 09:34:02,956] {standard_task_runner.py:52} INFO - Started process 997 to run task
[2022-10-17 09:34:03,030] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'create_table', 'backfill__2022-09-17T00:00:00+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp1kpsbayx', '--error-file', '/tmp/tmpjqjubr_n']
[2022-10-17 09:34:03,041] {standard_task_runner.py:80} INFO - Job 33: Subtask create_table
[2022-10-17 09:34:03,311] {task_command.py:369} INFO - Running <TaskInstance: my_first_dag.create_table backfill__2022-09-17T00:00:00+00:00 [running]> on host 48b5b9061ccc
[2022-10-17 09:34:03,805] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-09-17T00:00:00+00:00
[2022-10-17 09:34:03,840] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-17 09:34:03,854] {dbapi.py:208} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS users2 (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-10-17 09:34:03,864] {postgres.py:94} INFO - NOTICE:  relation "users2" already exists, skipping

[2022-10-17 09:34:03,896] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_table, execution_date=20220917T000000, start_date=20221017T093402, end_date=20221017T093403
[2022-10-17 09:34:04,011] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-17 09:34:04,160] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
